-- Insert fake data into UserAccount table
INSERT INTO UserAccount (um_email, user_type) VALUES
('user1@example.com', 'student'),
('user2@example.com', 'professor'),
('user3@example.com', 'student'),
('user4@example.com', 'student'),
('user5@example.com', 'professor'),
('user6@example.com', 'student'),
('user7@example.com', 'professor'),
('user8@example.com', 'student'),
('user9@example.com', 'student'),
('user10@example.com', 'professor'),
('user11@example.com', 'student'),
('user12@example.com', 'student'),
('user13@example.com', 'professor'),
('user14@example.com', 'student'),
('user15@example.com', 'student'),
('user16@example.com', 'professor'),
('user17@example.com', 'student'),
('user18@example.com', 'student'),
('user19@example.com', 'professor'),
('user20@example.com', 'student');

-- Insert fake data into Classes table
INSERT INTO Classes (class_name, class_term, class_professor) VALUES
('Mathematics', 'Spring 2024', 'Professor Smith'),
('History', 'Spring 2024', 'Professor Johnson'),
('Computer Science', 'Spring 2024', 'Professor Williams'),
('Physics', 'Spring 2024', 'Professor Brown'),
('Biology', 'Spring 2024', 'Professor Davis'),
('Chemistry', 'Spring 2024', 'Professor Wilson'),
('English Literature', 'Spring 2024', 'Professor Martinez'),
('Art History', 'Spring 2024', 'Professor Anderson'),
('Economics', 'Spring 2024', 'Professor Thompson'),
('Psychology', 'Spring 2024', 'Professor White'),
('Anthropology', 'Spring 2024', 'Professor Garcia'),
('Sociology', 'Spring 2024', 'Professor Lee'),
('French', 'Spring 2024', 'Professor Clark'),
('Geography', 'Spring 2024', 'Professor Hall'),
('Music', 'Spring 2024', 'Professor Allen'),
('Philosophy', 'Spring 2024', 'Professor Adams'),
('Artificial Intelligence', 'Spring 2024', 'Professor Turner'),
('Data Science', 'Spring 2024', 'Professor Cooper'),
('Astronomy', 'Spring 2024', 'Professor Scott'),
('Physical Education', 'Spring 2024', 'Professor King');

-- Insert fake data into MyClasses table
INSERT INTO MyClasses (user_id, class_id) VALUES
(1, 1),
(1, 3),
(2, 2),
(3, 4),
(4, 5),
(5, 1),
(5, 3),
(6, 6),
(6, 8),
(7, 7),
(8, 9),
(9, 10),
(10, 2),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20);

-- Insert fake data into Notes table
INSERT INTO Notes (date_created, note_title, note_content, verification, user_id, class_id) VALUES
('2024-03-20 08:00:00', 'Mathematics Lecture 1 Notes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 1, 1),
('2024-03-21 10:30:00', 'History Lecture 1 Notes', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, 2, 2),
('2024-03-22 12:00:00', 'Computer Science Lecture 1 Notes', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, 3, 3),
('2024-03-23 14:00:00', 'Physics Lecture 1 Notes', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 1, 4, 4),
('2024-03-24 16:00:00', 'Biology Lecture 1 Notes', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1, 5, 5),
('2024-03-25 18:00:00', 'Chemistry Lecture 1 Notes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 6, 6),
('2024-03-26 20:00:00', 'English Literature Lecture 1 Notes', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, 7, 7),
('2024-03-27 22:00:00', 'Art History Lecture 1 Notes', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, 8, 8),
('2024-03-28 10:00:00', 'Economics Lecture 1 Notes', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 1, 9, 9),
('2024-03-29 12:00:00', 'Psychology Lecture 1 Notes', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1, 10, 10),
('2024-03-30 14:00:00', 'Anthropology Lecture 1 Notes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 11, 11),
('2024-03-31 16:00:00', 'Sociology Lecture 1 Notes', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, 12, 12),
('2024-04-01 18:00:00', 'French Lecture 1 Notes', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, 13, 13),
('2024-04-02 20:00:00', 'Geography Lecture 1 Notes', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 1, 14, 14),
('2024-04-03 10:00:00', 'Music Lecture 1 Notes', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1, 15, 15),
('2024-04-04 12:00:00', 'Philosophy Lecture 1 Notes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 16, 16),
('2024-04-05 14:00:00', 'Artificial Intelligence Lecture 1 Notes', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, 17, 17),
('2024-04-06 16:00:00', 'Data Science Lecture 1 Notes', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, 18, 18),
('2024-04-07 18:00:00', 'Astronomy Lecture 1 Notes', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 1, 19, 19),
('2024-04-08 10:00:00', 'Physical Education Lecture 1 Notes', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1, 20, 20);

-- Insert fake data into Request_Reports table
INSERT INTO Request_Reports (request_content, status, note_id, user_id) VALUES
('Please review my Mathematics lecture notes.', 'Pending', 1, 1),
('Could you provide feedback on my History lecture notes?', 'In Progress', 2, 2),
('I need assistance with understanding a concept in Computer Science.', 'Resolved', 3, 3),
('Can you clarify a point from the Physics lecture?', 'Pending', 4, 4),
('I have a question about the Biology lecture material.', 'Resolved', 5, 5),
('Please check my Chemistry lecture notes for accuracy.', 'Pending', 6, 6),
('I need feedback on my English Literature assignment.', 'In Progress', 7, 7),
('Could you help me with my Art History project?', 'Resolved', 8, 8),
('I need guidance on the Economics lecture material.', 'Pending', 9, 9),
('I\'m struggling with understanding concepts in Psychology.', 'Resolved', 10, 10),
('Please assist with Anthropology lecture content.', 'Pending', 11, 11),
('I\'m confused about Sociology lecture topics.', 'In Progress', 12, 12),
('Could you review my French lecture notes?', 'Resolved', 13, 13),
('I need clarification on Geography lecture material.', 'Pending', 14, 14),
('Can you provide feedback on my Music lecture notes?', 'Resolved', 15, 15),
('Please help with Philosophy lecture content.', 'Pending', 16, 16),
('I\'m seeking assistance with Artificial Intelligence concepts.', 'In Progress', 17, 17),
('Could you provide guidance on Data Science assignments?', 'Resolved', 18, 18),
('I have questions about Astronomy lecture material.', 'Pending', 19, 19),
('Please review my Physical Education notes.', 'Resolved', 20, 20);
